import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 'rakhi-001',
    name: '001 Charming Shubh Premium Rakhi',
    description: 'A classic Rakhi with a timeless design, perfect for traditional celebrations.',
    price: 50,
    image: 'images/r1.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-002',
    name: '002 Royal Turtle Premium Rakhi',
    description: 'A unique Rakhi featuring elegant turtle charms and colorful beads.',
    price: 45,
    image: '/images/r2.jpg',
    keywords: ['designer', 'kids'],
  },
  {
    id: 'rakhi-003',
    name: '003 Divine Radhe Rakhi',
    description: 'An exquisite designer Rakhi with "Radhe" inscribed, for a special brother.',
    price: 40,
    image: '/images/r3.jpg',
    keywords: ['divine', 'traditional'],
  },
  {
    id: 'rakhi-004',
    name: '004 Graceful Ganesha Rakhi',
    description: 'A classic Rakhi with a divine Ganesha charm, perfect for blessings.',
    price: 40,
    image: '/images/r4.jpg',
    keywords: ['divine', 'kids'],
  },
  {
    id: 'rakhi-005',
    name: '005 Sterling Silver Charm Rakhi',
    description: 'A premium, fancy Rakhi in silver with a striking red centerpiece.',
    price: 50,
    image: '/images/r5.jpg',
    keywords: ['designer', 'silver'],
  },
  {
    id: 'rakhi-006',
    name: '006 Tom & Jerry Kids Rakhi',
    description: 'Let your little brother show off his favorite cartoon duo.',
    price: 30,
    image: '/images/r6.jpg',
    keywords: ['kids', 'cartoon'],
  },
  {
    id: 'rakhi-007',
    name: '007 Sacred Designer Rakhi',
    description: 'A simple yet elegant Rakhi made with a central rectangular stone.',
    price: 40,
    image: '/images/r7.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-008',
    name: '008 Doraemon Light-Up Kids Rakhi',
    description: 'A fun, light-up Doraemon Rakhi for the little adventurer.',
    price: 20,
    image: '/images/r8.jpg',
    keywords: ['kids', 'cartoon', 'light-up'],
  },
  {
    id: 'rakhi-009',
    name: '009 Mickey Mouse Light-Up Kids Rakhi',
    description: 'A magical, light-up Mickey Mouse Rakhi for your little brother.',
    price: 20,
    image: '/images/r9.jpg',
    keywords: ['kids', 'cartoon', 'light-up'],
  },
  {
    id: 'rakhi-010',
    name: '010 Radiant Pearl Designer Rakhi',
    description: 'An exquisite designer Rakhi with pearls and colorful beads.',
    price: 35,
    image: '/images/r10.jpg',
    keywords: ['designer', 'traditional'],
  },
  {
    id: 'rakhi-011',
    name: '011 Colorful Floral Rakhi',
    description: 'A vibrant Rakhi with a multi-colored floral centerpiece and stones.',
    price: 30,
    image: '/images/r11.jpg',
    keywords: ['designer', 'floral', 'stone work'],
  },
  {
    id: 'rakhi-012',
    name: '012 Rudraksha Fusion Rakhi',
    description: 'Traditional Rudraksha beads meet modern stone work for a divine look.',
    price: 30,
    image: '/images/r12.jpg',
    keywords: ['traditional', 'divine', 'stone work'],
  },
  {
    id: 'rakhi-013',
    name: '013 Enamel Flower Rakhi',
    description: 'Elegant Rakhi with beautiful red and green enamel work on a floral design.',
    price: 30,
    image: '/images/r13.jpg',
    keywords: ['designer', 'floral'],
  },
  {
    id: 'rakhi-014',
    name: '014 Sandalwood Serenity Rakhi',
    description: 'A simple and elegant Rakhi made from calming sandalwood beads.',
    price: 20,
    image: '/images/r14.jpg',
    keywords: ['traditional', 'eco-friendly'],
  },
  {
    id: 'rakhi-015',
    name: '015 Rose Gold Floral Rakhi',
    description: 'A stunning rose gold Rakhi with a floral centerpiece and stone accents.',
    price: 15,
    image: '/images/r15.jpg',
    keywords: ['designer', 'floral', 'stone work'],
  },
  {
    id: 'rakhi-016',
    name: '016 Auspicious Om Rakhi',
    description: 'A sacred Rakhi featuring the Om symbol for peace and protection.',
    price: 10,
    image: '/images/r16.jpg',
    keywords: ['divine', 'traditional'],
  },
  {
    id: 'rakhi-017',
    name: '017 Family Rakhi Set (Set of 5)',
    description: 'A beautiful set of 5 matching Rakhis with heart and swastik motifs.',
    price: 10,
    image: '/images/r17.jpg',
    keywords: ['traditional', 'divine', 'set'],
  },
  {
    id: 'rakhi-018',
    name: '018 Playful Turtle Rakhi Set (Set of 5)',
    description: 'A fun set of 5 Rakhis featuring adorable turtle charms.',
    price: 10,
    image: '/images/r18.jpg',
    keywords: ['kids', 'set'],
  },
  {
    id: 'rakhi-019',
    name: '019 Cool "BRO" Rakhi',
    description: 'A trendy and modern Rakhi that says it all. For the coolest brother.',
    price: 10,
    image: '/images/r19.jpg',
    keywords: ['designer', 'kids'],
  },
  {
    id: 'rakhi-020',
    name: '020 Divine Trishul Rakhi',
    description: 'A powerful Rakhi featuring Lord Shiva\'s Trishul for strength and protection.',
    price: 10,
    image: '/images/r20.jpg',
    keywords: ['divine', 'traditional'],
  },
  {
    id: 'rakhi-021',
    name: '021 Regal Red Stone Rakhi',
    description: 'A luxurious Rakhi with golden beads and a brilliant red stone centerpiece.',
    price: 20,
    image: '/images/r21.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-022',
    name: '022 Classic Om Symbol Rakhi',
    description: 'A traditional Om Rakhi with vibrant yellow and red threads.',
    price: 10,
    image: '/images/r22.jpg',
    keywords: ['divine', 'traditional'],
  },
  {
    id: 'rakhi-023',
    name: '023 Golden Ganesha Rakhi',
    description: 'A brilliant golden Rakhi with an embossed Ganesha and pearl accents.',
    price: 40,
    image: '/images/r23.jpg',
    keywords: ['divine', 'stone work'],
  },
  {
    id: 'rakhi-024',
    name: '024 Pearl and Petal Rakhi',
    description: 'An elegant Rakhi featuring pearls and colorful enamel petals.',
    price: 30,
    image: '/images/r24.jpg',
    keywords: ['designer', 'traditional'],
  },
  {
    id: 'rakhi-025',
    name: '025 Festive Orange Lumba Rakhi',
    description: 'A gorgeous Lumba Rakhi with intricate goldwork and a festive orange tassel.',
    price: 25,
    image: '/images/r25.jpg',
    keywords: ['lumba', 'designer'],
  },
  {
    id: 'rakhi-026',
    name: '026 Sacred Rudraksha Rakhi Pack',
    description: 'A bulk pack of traditional Rudraksha Rakhis for the whole family.',
    price: 10,
    image: '/images/r26.jpg',
    keywords: ['traditional', 'divine', 'set'],
  },
  {
    id: '027 rakhi-027',
    name: 'Glittering Ram Sita Ram Decor',
    description: 'A spiritual decorative patch with "Ram Ram Sita Ram" in golden glitter.',
    price: 20,
    image: '/images/r27.jpg',
    keywords: ['divine', 'spiritual decor'],
  },
  {
    id: 'rakhi-028',
    name: '028 Glittering Ram Ram Hexagon Decor',
    description: 'A hexagonal spiritual decorative patch with "Ram Ram" in golden glitter.',
    price: 15,
    image: '/images/r28.jpg',
    keywords: ['divine', 'spiritual decor'],
  },
  {
    id: 'rakhi-029',
    name: '029 Glittering Swastik Ram Decor',
    description: 'A Swastik-shaped spiritual patch with "Ram Ram" in golden glitter.',
    price: 15,
    image: '/images/r29.jpg',
    keywords: ['divine', 'spiritual decor'],
  },
  {
    id: 'rakhi-030',
    name: '030 Glittering Temple Ram Decor',
    description: 'A temple-shaped spiritual patch with "Ram Ram" in golden glitter.',
    price: 20,
    image: '/images/r30.jpg',
    keywords: ['divine', 'spiritual decor'],
  },
  {
    id: 'rakhi-031',
    name: '031 Glittering Jai Shri Ram Decor',
    description: 'An arch-shaped spiritual patch with "Shri Ram Jai Ram Sita Ram" in golden glitter.',
    price: 20,
    image: '/images/r31.jpg',
    keywords: ['divine', 'spiritual decor'],
  },
  {
    id: 'rakhi-032',
    name: 'Olive Green Lumba Set',
    description: 'A set of elegant Lumba Rakhis in a beautiful olive green hue with pearl accents.',
    price: 20,
    image: '/images/r32.jpg',
    keywords: ['lumba', 'set'],
  },
  {
    id: 'rakhi-033',
    name: 'Royal Red & Gold Lumba Set',
    description: 'A set of royal Lumba Rakhis with rich red beads and golden details.',
    price: 20,
    image: '/images/r33.jpg',
    keywords: ['lumba', 'set', 'designer'],
  },
  {
    id: 'rakhi-034',
    name: 'Crystal Snowflake Lumba Set',
    description: 'A dazzling set of Lumba Rakhis with clear crystal beads and snowflake motifs.',
    price: 15,
    image: '/images/r34.jpg',
    keywords: ['lumba', 'set', 'stone work'],
  },
  {
    id: 'rakhi-035',
    name: 'Azure Blue Lumba Set',
    description: 'A stunning set of Lumba Rakhis in azure blue with silver accents and pearls.',
    price: 15,
    image: '/images/r35.jpg',
    keywords: ['lumba', 'set', 'silver'],
  },
  {
    id: 'rakhi-036',
    name: 'Colorful Evil Eye Lumba Set',
    description: 'A vibrant set of Lumba Rakhis with multi-colored beads to ward off the evil eye.',
    price: 20,
    image: '/images/r36.jpg',
    keywords: ['lumba', 'set', 'evil eye'],
  },
  {
    id: 'rakhi-037',
    name: 'Classic Gold & White Lumba Set',
    description: 'A timeless set of Lumba Rakhis with elegant white and golden beads.',
    price: 20,
    image: '/images/r37.jpg',
    keywords: ['lumba', 'set', 'designer'],
  },
  {
    id: 'rakhi-038',
    name: 'Chhota Bheem Kids Rakhi',
    description: 'For the little hero, a Rakhi featuring the mighty Chhota Bheem on his cycle.',
    price: 40,
    image: '/images/r38.jpg',
    keywords: ['kids', 'cartoon'],
  },
  {
    id: 'rakhi-039',
    name: 'Anime Hero Kids Rakhi',
    description: 'A bright and cheerful light-up Rakhi for fans of anime heroes.',
    price: 20,
    image: '/images/r39.jpg',
    keywords: ['kids', 'cartoon', 'light-up'],
  },
  {
    id: 'rakhi-040',
    name: 'Superman Kids Rakhi',
    description: 'A super Rakhi for a super brother, featuring the iconic Superman logo.',
    price: 20,
    image: '/images/r40.jpg',
    keywords: ['kids', 'cartoon', 'superhero'],
  },
  {
    id: 'rakhi-041',
    name: 'Pokemon Trainer Kids Rakhi',
    description: 'Gotta catch \'em all! A cool Rakhi for the aspiring Pokemon trainer.',
    price: 20,
    image: '/images/r41.jpg',
    keywords: ['kids', 'cartoon'],
  },
  {
    id: 'rakhi-042',
    name: 'Minimalist Wooden Bead Rakhi',
    description: 'A simple, earthy Rakhi with classic wooden beads for a minimalist look.',
    price: 10,
    image: '/images/r42.jpg',
    keywords: ['traditional', 'eco-friendly'],
  },
  {
    id: 'rakhi-043',
    name: 'Crimson Stone & Gold Rakhi',
    description: 'A beautiful Rakhi combining golden beads with sparkling crimson stones.',
    price: 12,
    image: '/images/r43.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-044',
    name: 'Jeweled Peacock Rakhi',
    description: 'An ornate Rakhi with a stunning peacock design and premium packaging.',
    price: 40,
    image: '/images/r44.jpg',
    keywords: ['designer', 'stone work', 'divine'],
  },
  {
    id: 'rakhi-045',
    name: 'Blue Evil Eye Protection Set',
    description: 'A beautiful set of Rakhis with the protective Evil Eye charm and blue beads.',
    price: 40,
    image: '/images/r45.jpg',
    keywords: ['evil eye', 'set'],
  },
  {
    id: 'rakhi-046',
    name: 'Silver Evil Eye Rakhi Set',
    description: 'A stylish set of silver-beaded Rakhis featuring the dark blue Evil Eye.',
    price: 25,
    image: '/images/r46.jpg',
    keywords: ['evil eye', 'set', 'silver'],
  },
  {
    id: 'rakhi-047',
    name: 'Joyful Ganesha Rakhi',
    description: 'A cheerful Rakhi with a red Ganesha charm and colorful beads.',
    price: 30,
    image: '/images/r47.jpg',
    keywords: ['divine', 'kids'],
  },
  {
    id: 'rakhi-048',
    name: 'Enamel Peacock Rakhi',
    description: 'A majestic Rakhi with a beautifully detailed enamel peacock centerpiece.',
    price: 40,
    image: '/images/r48.jpg',
    keywords: ['designer', 'divine'],
  },
  {
    id: 'rakhi-049',
    name: 'Symmetric Stone Work Rakhi',
    description: 'An elegant Rakhi with intricate, symmetric stone work on a golden thread.',
    price: 40,
    image: '/images/r49.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-050',
    name: 'Ornate Blue Evil Eye Rakhi',
    description: 'A designer Rakhi with a prominent Evil Eye charm set in an ornate golden frame.',
    price: 35,
    image: '/images/r50.jpg',
    keywords: ['evil eye', 'designer'],
  },
  {
    id: 'rakhi-051',
    name: 'Vibrant Floral Stone Rakhi',
    description: 'A vibrant floral Rakhi featuring red and green stones and pearl beads.',
    price: 35,
    image: '/images/r51.jpg',
    keywords: ['designer', 'stone work', 'floral'],
  },
  {
    id: 'rakhi-052',
    name: 'Elegant Evil Eye Rakhi',
    description: 'A chic and modern Rakhi with a leaf-shaped Evil Eye charm and white beads.',
    price: 20,
    image: '/images/r52.jpg',
    keywords: ['evil eye', 'designer'],
  },
  {
    id: 'rakhi-053',
    name: 'Sparkling Diamond-Cut Rakhi',
    description: 'A glittering Rakhi featuring diamond-cut stones for maximum sparkle.',
    price: 35,
    image: '/images/r53.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-054',
    name: 'Silver Peacock Bracelet Rakhi',
    description: 'A stylish silver bracelet Rakhi with a beautiful peacock charm.',
    price: 30,
    image: '/images/r54.jpg',
    keywords: ['designer', 'silver', 'divine'],
  },
  {
    id: 'rakhi-055',
    name: 'Sandalwood Om Rakhi',
    description: 'A calming Rakhi featuring a wooden Om centerpiece and sandalwood beads.',
    price: 25,
    image: '/images/r55.jpg',
    keywords: ['divine', 'traditional', 'eco-friendly'],
  },
  {
    id: 'rakhi-056',
    name: 'Silver & Ruby Stone Rakhi',
    description: 'A sophisticated silver and gold tone Rakhi with ruby-red stones.',
    price: 30,
    image: '/images/r56.jpg',
    keywords: ['designer', 'silver', 'stone work'],
  },
  {
    id: 'rakhi-057',
    name: 'Traditional Kundan Rakhi',
    description: 'A timeless Rakhi featuring traditional Kundan work with red and green beads.',
    price: 30,
    image: '/images/r57.jpg',
    keywords: ['designer', 'stone work', 'traditional'],
  },
  {
    id: 'rakhi-058',
    name: 'Golden Filigree Stone Rakhi',
    description: 'An intricate Rakhi with delicate golden filigree work around a central stone.',
    price: 30,
    image: '/images/r58.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-059',
    name: 'Dapper Bow-Tie Rakhi',
    description: 'A unique and stylish Rakhi designed like a bow-tie with pearl and stone details.',
    price: 25,
    image: '/images/r59.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-060',
    name: 'Tricolor Bead Rakhi',
    description: 'A simple yet elegant Rakhi with sparkling stones and red & green beads.',
    price: 30,
    image: '/images/r60.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
    id: 'rakhi-061',
    name: 'Earthy Wooden Bead Rakhi',
    description: 'A minimalist Rakhi with earthy wooden beads and decorative tassels.',
    price: 20,
    image: '/images/r61.jpg',
    keywords: ['traditional', 'eco-friendly'],
  },
  {
    id: 'rakhi-062',
    name: 'Golden Square Stone Rakhi',
    description: 'A modern Rakhi design with a prominent square stone and sparkling accents.',
    price: 35,
    image: '/images/r62.jpg',
    keywords: ['designer', 'stone work'],
  },
  {
  id: 'rakhi-063',
  name: 'Elegant Designer Rakhi 63',
  description: 'An exquisite Rakhi crafted for a special brother, showcasing traditional design with modern flair.',
  price: 25,
  image: '/images/r63.jpg',
  keywords: ['designer', 'traditional'],
},
{
  id: 'rakhi-064',
  name: 'Classic Rakhi 64',
  description: 'A timeless Rakhi perfect for traditional celebrations, with elegant thread and design.',
  price: 20,
  image: '/images/r64.jpg',
  keywords: ['designer', 'classic'],
},
{
  id: 'rakhi-065',
  name: 'Fancy Rakhi 65',
  description: 'Premium fancy Rakhi featuring intricate details and a stunning centerpiece.',
  price: 25,
  image: '/images/r65.jpg',
  keywords: ['fancy', 'premium', 'intricate'],
},
{
  id: 'rakhi-066',
  name: 'Graceful Rakhi 66',
  description: 'Designed for a special brother, this Rakhi blends tradition with elegance.',
  price: 20,
  image: '/images/r66.jpg',
  keywords: ['designer', 'elegant'],
},
{
  id: 'rakhi-067',
  name: 'Timeless Rakhi 67',
  description: 'Celebrate with this classic Rakhi design that reflects tradition and warmth.',
  price: 50,
  image: '/images/r67.jpg',
  keywords: ['designer', 'classic'],
},
{
  id: 'rakhi-068',
  name: 'Fancy Rakhi 68',
  description: 'This fancy Rakhi shines with artistic craftsmanship and rich detailing.',
  price: 50,
  image: '/images/r68.jpg',
  keywords: ['fancy', 'artistic'],
},
{
  id: 'rakhi-069',
  name: 'Stylish Rakhi 69',
  description: 'A designer Rakhi that blends tradition and style, perfect for your brother.',
  price: 30,
  image: '/images/r69.jpg',
  keywords: ['designer', 'stylish'],
},
{
  id: 'rakhi-070',
  name: 'Royal Rakhi 70',
  description: 'A timeless Rakhi crafted for elegance and celebration.',
  price: 50,
  image: '/images/r70.jpg',
  keywords: ['designer', 'royal', 'classic'],
},
{
  id: 'rakhi-071',
  name: 'Fancy Rakhi 71',
  description: 'Crafted with detailed finesse, this Rakhi is a premium choice for festive gifting.',
  price: 25,
  image: '/images/r71.jpg',
  keywords: ['fancy', 'premium'],
},
{
  id: 'rakhi-072',
  name: 'Simple Rakhi 72',
  description: 'A beautiful yet budget-friendly Rakhi for expressing your love.',
  price: 8,
  image: '/images/r72.jpg',
  keywords: ['designer', 'simple'],
},
{
  id: 'rakhi-073',
  name: 'Classic Rakhi 73',
  description: 'A traditionally designed Rakhi perfect for expressing sibling love.',
  price: 25,
  image: '/images/r73.jpg',
  keywords: ['designer', 'traditional'],
},
{
  id: 'rakhi-074',
  name: 'Budget Fancy Rakhi 74',
  description: 'An affordable yet fancy Rakhi with eye-catching details.',
  price: 8,
  image: '/images/r74.jpg',
  keywords: ['fancy', 'budget'],
},
{
  id: 'rakhi-075',
  name: 'Designer Rakhi 75',
  description: 'Exquisitely crafted designer Rakhi for your loving brother.',
  price: 25,
  image: '/images/r75.jpg',
  keywords: ['designer', 'elegant'],
},
{
  id: 'rakhi-076',
  name: 'Traditional Rakhi 76',
  description: 'Classic Rakhi design with a focus on simplicity and tradition.',
  price: 10,
  image: '/images/r76.jpg',
  keywords: ['designer', 'traditional'],
},
{
  id: 'rakhi-077',
  name: 'Fancy Rakhi 77',
  description: 'A fancy Rakhi with stylish charm and intricate work, perfect for celebrations.',
  price: 10,
  image: '/images/r77.jpg',
  keywords: ['fancy', 'stylish'],
},
{
  id: 'rakhi-078',
  name: 'Elegant Rakhi 78',
  description: 'Celebrate Raksha Bandhan with this elegantly designed Rakhi for your brother.',
  price: 10,
  image: '/images/r78.jpg',
  keywords: ['designer', 'elegant'],
},

];
